server:
  port: 8888
spring:
  application:
    name: hug-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hugwh/hug-config-remote.git
          search-paths: '{application}'
          username: hugwh
          password: Hwh118122
    bus:
      enabled: false
      trace:
        enabled: false
    #spring cloud bus 刷新配置
#  rabbitmq:
#    host: 120.79.197.55
#    port: 5672
#    username: guest
#    password: guest
#management:
#  #spring boot admin监控配置
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
eureka:
  client:
    service-url:
      defaultZone: http://hugEureka01.com/eureka/