server:
  port: 1002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: hug-wechat-client
feign:
  hystrix:
    enabled: true
test:
  value: test-value