server:
  port: 80012
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: hug-demo-client
  cloud:
    config:
      uri: http://localhost:8888/
      profile: dev
      label: master
feign:
  hystrix:
    enabled: true
test:
  value: test-value