server:
  port: 8001
eureka:
  instance:
    hostname: hugEureka01.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: hug-eureka
